networks:
  default:
    name: breadcrumb_default

services:

  php-fpm:
    build:
      context: ./docker/dev/php
      dockerfile: Dockerfile
      target: fpm
      args:
        WWWUSER: "${WWWUSER:-1000}"
        WWWGROUP: "${WWWGROUP:-1000}"
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ".:/application"
      - "./docker/dev/php/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
